### ISSUE TITLE
Which SuiteSparse:GraphBLAS major version to target

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#100]
Currently, the repository uses a mix of v3.3.3 (stable) and 4.0.0 beta. The latter is used the GAP BFS tests.

To make sure that CI isn't constantly red, I'm currently dropping the BFS tests before running the tests:
https://github.com/GraphBLAS/LAGraph/blob/c6115e9056ce95b7c6df1d6fd241cde21f241d87/.travis.yml#L25

There was also a problem with the Mac OS build for these tests but this might be resolved as a side effect of migrating to 4.0:
```console
Undefined symbols for architecture x86_64:
  "_omp_get_wtime", referenced from:
      _bfs_log_parent in bfs_log_parent.c.o
```

**Comment by DrTimothyAldenDavis** [comment]
Sounds fine.  A published version of v4 will take me a while to write, so keeping the tests at v3.3.3 is fine.

**Comment by szarnyasg** [comment]
Okay, great. Version 3.3.3 works fine at the moment (CI finished successfully for new commits).
