### ISSUE TITLE
LAGraph_cc_fastsv defined in header but not .so-file

### ISSUE THREAD

**Issue by bergkvist** [GraphBLAS/LAGraph#107]
In the header file I see:
```
$ cat LAGraph.h | grep fastsv

GrB_Info LAGraph_cc_fastsv (
GrB_Info LAGraph_cc_fastsv2 (
GrB_Info LAGraph_cc_fastsv3 (
GrB_Info LAGraph_cc_fastsv4 (
GrB_Info LAGraph_cc_fastsv5 (
GrB_Info LAGraph_cc_fastsv5a (
GrB_Info LAGraph_cc_fastsv5b (
```

But in the shared library only the last of these symbols are available:
```
$ nm -D liblagraph.so | grep fastsv

000000000001e250 T LAGraph_cc_fastsv5b
```

I'm using the latest tagged version (4Jan2021) from the docker image (https://hub.docker.com/r/graphblas/lagraph)

**Comment by bergkvist** [comment]
It also seems like santize=true in LAGraph_cc_fastsv5b doesn't work.
```c
GrB_Info LAGraph_cc_fastsv5b (
    GrB_Vector *result,     // output: array of component identifiers
    GrB_Matrix *A,          // input matrix
                            //   content remains the same, but pointer changes
    bool sanitize           // if true, ensure A is symmetric
) ;
```

**Comment by DrTimothyAldenDavis** [comment]
This is expected.  All of those functions will be revised, and experimental
ones get dropped as we go.  The LAGraph.h is a very rough draft.  The
updated API is in LAGraph2.h, likely not in any docker image yet.

**Comment by DrTimothyAldenDavis** [comment]
Fixed.  One version now appears (it was fastSV5b if I recall), now called LG_CC_FastSV, but we should go back and review the prior methods as we update the current LG_CC_FastSV.  There might be some ideas there as we transition the whole method so it uses mainly calls to GraphBLAS instead of doing the work itself.
