### ISSUE TITLE
potential bugs

### ISSUE THREAD

**Issue by cjh10644** [GraphBLAS/LAGraph#111]
https://github.com/GraphBLAS/LAGraph/blob/666b4a1fd0c7c27395dc912ecfca2cfe108dd3e4/Experimental/Utility/LAGraph_mmread.c#L941

should this line be 
if (nrows == 0 || ncols == 0 || nvals == 0)

**Comment by szarnyasg** [comment]
@cjh10644 thanks for reporting this. @sei-smcmillan and others are working on restructuring the code base now, so let's defer fixing this until those are merged.

**Comment by DrTimothyAldenDavis** [comment]
Fixed, in my next push.
