### ISSUE TITLE
Algorithm setups

### ISSUE THREAD

**Issue by ayasar70** [GraphBLAS/LAGraph#113]
Hello,

I would like to run breadth-first search, connected components and triangle counting algorithms. Which implementations should I use? What are the parameters/setup for the best performance?

Thanks in advance!

-- a

**Comment by DrTimothyAldenDavis** [comment]
Use the methods in the LAGraph/Experimental2 folder, and using the LAGraph/Test2 tests.  Those all have scripts that run the GAP benchmarks for these methods.  Be sure the use the latest stable version of SuiteSparse:GraphBLAS, v4.0.3.

**Comment by DrTimothyAldenDavis** [comment]
There are many triangle counting methods in the LAGraph_TriangleCount_Methods function.  See the Test2/TriangleCount/test_tc.c for the ones I tend to use for the GAP benchmarks.  The default is method 5, the "SandiaDot" method, but other methods can sometimes be faster for some matrices.

**Comment by ayasar70** [comment]
Thank you!
