### ISSUE TITLE
Is Experimental2 and Test2 the latest to use? 

### ISSUE THREAD

**Issue by kakulo** [GraphBLAS/LAGraph#118]
Hi, I am using LAGraph for a study. I find two versions of Experimentals and Tests (Experiemntal and Test vs. Experiemntal2 and Test2) under the repo. I am confused about which one to use. Is the Experiemntal2 and Test2 the latest one? Also, which is the one you used in the IISWC benchmarking paper? Is it the Experimental and Test? Thank you very much for help :)

**Comment by DrTimothyAldenDavis** [comment]
You need to use the 'reorg' branch, which is what we used for the IISWC paper.

**Comment by DrTimothyAldenDavis** [comment]
I've just change the default branch to 'reorg'.
