### ISSUE TITLE
Choosing a BFS algorithm

### ISSUE THREAD

**Issue by jeffreylovitz** [GraphBLAS/LAGraph#119]
RedisGraph is currently using LAGraph's older BFS push-pull algorithm - https://github.com/GraphBLAS/LAGraph/blob/6a07dc4b737bce1931c538826e68e177d5d57620/Source/Algorithm/LAGraph_bfs_pushpull.c .

We have seen a few issues, such as https://github.com/RedisGraph/RedisGraph/issues/1912 and https://github.com/RedisGraph/RedisGraph/issues/1695, which seem to indicate a bug in this algorithm. Using your latest work seems like a sensible solution, but there are now several BF variants, and we are unsure which to adopt.

In most cases we want the vector of parents to backtrack through, though this is not always true. We can adopt two algorithms to handle these two cases if that's a preferred solution.

Thanks for your guidance!

**Comment by DrTimothyAldenDavis** [comment]
Yes, that one is old and should be replaced by the LAGraph_BreadthFirstSearch.c in the reorg branch of LAGraph, in the src/algorithm folder.  It has both the parent version and level-only variants.

**Comment by jeffreylovitz** [comment]
@DrTimothyAldenDavis Thanks for the help!

**Comment by DrTimothyAldenDavis** [comment]
The older BFS shouldn't have this problem, but you might be using it
incorrectly.
In that case, the new one would have the same problem.

The method ignores any edge weights.  If you have an edge of zero, or
infinite, weight
to indicate "it's not really an edge", then the BFS will see it as an edge
anyway, and follow it.
