### ISSUE TITLE
CMake Error install target does not exist

### ISSUE THREAD

**Issue by pcostanza** [GraphBLAS/LAGraph#126]
I am trying to follow the build instructions. However, I see the following error message:

``
CMake Error at CMakeLists.txt:264 (install):
  install TARGETS given target "lagraph" which does not exist in this
  directory.
``

I have cmake version 3.10.2.

What's the issue here? I don't know cmake very well...

Thanks,
Pascal

**Comment by szarnyasg** [comment]
Hi @pcostanza, try following the CI job's commands:
https://github.com/GraphBLAS/LAGraph/blob/reorg/.github/workflows/build.yml
Gabor

**Comment by pcostanza** [comment]
Hi @szarnyasg, what I'm seeing in the run section for the Build Project part looks more or less the same as what I'm trying to do myself. When I run the following, I get the same error:

``
cmake .. -DGRAPHBLAS_INCLUDE_DIR=/home/pcostanz/include -DGRAPHBLAS_LIBRARY=/home/pcostanz/lib
``

**Comment by szarnyasg** [comment]
Probably not too helpful but... on Fedora with CMake 3.22, this works:
```bash
mkdir build
cd build
cmake ..
make
```

**Comment by szarnyasg** [comment]
SO tells me this is fixed in CMake 3.13: https://stackoverflow.com/questions/34443128/cmake-install-targets-in-subdirectories

**Comment by pcostanza** [comment]
I had a different issue with cmake 3.22, but with cmake 3.16, this now works. Thanks a lot for the help!

**Comment by DrTimothyAldenDavis** [comment]
I've updated the CMakeLists.txt so that it requires cmake 3.13.
