### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#127]
While troubleshooting #126, I tried to do a build on Apple Silicon (M1, etc.). 

By default, `omp.h` is missing due to the problem described at https://mac.r-project.org/openmp/. I tried the workaround on the website but could not get it working.

The following approach works but it's not exactly portable:
```bash
brew install libomp
```
```bash
ag -l omp.h | xargs gsed -i 's|<omp.h>|"/opt/homebrew/include/omp.h"|'
mkdir build
cd build
cmake .. -DGRAPHBLAS_INCLUDE_DIR=~/git/GraphBLAS/Include -DGRAPHBLAS_LIBRARY=~/git/GraphBLAS/./build/libgraphblas.dylib
make
```

**Comment by DrTimothyAldenDavis** [comment]
What does "ag" do?  Make a list of files with "omp.h" I suppose?

Other than 2 files in the old/experimental_utility file, which are not compiled, only include/LAGraph.h as the "#include <omp.h>".  Maybe the sed edit could be replaced by an #ifdef in LAGraph.h itself.

**Comment by szarnyasg** [comment]
`ag` is essentially the same as `ack` but it claims to be faster. Here, using `ack 'omp.h' -l` would work just as well.
Using an ifdef is feasible -- I'll investigate whether there's a more elegant workaround.

**Comment by DrTimothyAldenDavis** [comment]
This now works in LAGraph v1.0.1.beta1, using either Apple clang or GNU gcc 12.2.0 and libgomp from homebrew.
