### ISSUE TITLE
Build issue with SuiteSparse

### ISSUE THREAD

**Issue by Glebanister** [GraphBLAS/LAGraph#128]
Hello, I want to run some benchmarks with LAGraph with SuiteSparse as GraphBLAS implementation. I have completed the following steps:

- Cloned LAGraph and SuiteSparse to my machine
- Checked out the latest versions of both libraries
- Built SuiteSparse/GraphBLAS
- Set the environment variable `GRAPHBLAS_ROOT` to the `SuiteSparse/GraphBLAS`
- Changed `LaGraph/CMakeLists.txt`: I have commented out line №111 with the following content:
```cmake
set ( ENV{GRAPHBLAS_ROOT} ${CMAKE_SOURCE_DIR}/../GraphBLAS )
```
Because it seems like it forces `GRAPHBLAS_ROOT` to be in the `${CMAKE_SOURCE_DIR}/../GraphBLAS `
- Successfully executed CMakeLists.txt (hence, it correctly found the `GRAPHBLAS_ROOT`, library and include path)
- Started build

But I keep getting the following errors:

```
LAGraph/include/LAGraph.h:59:6: error: #error "The GraphBLAS library must support the v2.0 C API Specification"
     #error "The GraphBLAS library must support the v2.0 C API Specification"

LAGraph/include/LAGraph.h:823:5: error: unknown type name ‘GrB_Scalar’; did you mean ‘GxB_Scalar’?
     GrB_Scalar s,           // scalar to query
     ^~~~~~~~~~
     GxB_Scalar
```

Could you, please, explain what am I doing wrong?

**Comment by szarnyasg** [comment]
Hi @Glebanister,

1. What OS are you running? I got this message on macOS when an old version of SuiteSparse:GraphBLAS was installed (I believe as a transitive dependency of a brew package).

2. You may want to try the instructions provided in the CI configurations. These use binary SuiteSparse:GraphBLAS packages from `conda` so they'll get you the latest stable but not the `master` one:
https://github.com/GraphBLAS/LAGraph/blob/reorg/.github/workflows/build.yml

Gabor

**Comment by DrTimothyAldenDavis** [comment]
The SuiteSparse meta-library itself ( https://github.com/DrTimothyAldenDavis/SuiteSparse ) is updated on a less frequent basis than the SuiteSparse:GraphBLAS library itself ( https://github.com/DrTimothyAldenDavis/GraphBLAS ).  You need to install the latest stable version of the latter.

In addition, many linux distros will have old versions of my libraries pre-installed.   My linux distro has GraphBLAS v1.0  for example, as a built-in library.

**Comment by DrTimothyAldenDavis** [comment]
Sorry for the mixup.  I'll update SuiteSparse with the latest v6.1.4 of GraphBLAS shortly.
