### ISSUE TITLE
LAGraph finalize doesn't reset bool LG_init_has_been_called

### ISSUE THREAD

**Issue by mcordery** [GraphBLAS/LAGraph#157]
A call to LAGr_init() sets the global boolean bool LG_init_has_been_called = true;
However, a subsequent call to LAGraph_finalize() does not reset the parameter to false.
This can cause problems in LAGr_init() which tests the value and returns with GrB_INVALID_VALUE if true.
This can cause later errors if, as in MMRead, initialize/finalize are called in sequence several times.
I would suggest putting in an

extern bool LG_init_has_been_called;
LAGraph_finalize()
{
...
LG_init_has_been_called = false;
...
}

**Comment by DrTimothyAldenDavis** [comment]
That's by design, because GrB_init and GrB_finalize can only be called once.  Once GrB_finalize has been called the GraphBLAS C API says that no other GrB method can be called, not even another call to GrB_init.
