### ISSUE TITLE
Run the JIT of SuiteSparse:GraphBLAS in CI

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#188]
LAGraph should be tested with the JIT coming out in SuiteSparse:GraphBLAS v8.0.0.

**Comment by DrTimothyAldenDavis** [comment]
The CI now downloads the latest GraphBLAS (currently 9.3.1), and compiles it from scratch in 'compact' mode.  In that mode, there are no 'factory kernels', so the JIT kernels are mostly used instead.
