### ISSUE TITLE
CC might have a bug

### ISSUE THREAD

**Issue by nicelhc13** [GraphBLAS/LAGraph#19]
Hello, 

I found a corner case which CC seems not running correctly.
Could you try the below matrix market case?
This is symmetric matrix.

4 4 6
1 4 1
2 3 1
3 4 1
3 2 1
4 1 1
4 3 1

Since all nodes are connected, the number of connected component should be 1, but, 
in case of commit number bfcbeaa5c1d9e24b23cb1c43b0861aab4c9b1a13, the CC calculates 2 connected components.

So I pulled the new commits and tried it again.
In this case, it prints 4.

If it is my mistake, then please ignore below one.
However, if it is, my idea may be the reason for that.

When CC does hooking between stars, assign() function updates parents for each node.
However, the assign() ignores the later assignment to the one entry.
Therefore, in the above case, even though the node 2 should update its parent to node 1 by node 3, it does not since the node 2 assigns its parent before the update.
The remaining updates to node 2 are ignored.

But, still I am not sure whether my idea is correct or not.
Thank you!

**Comment by szarnyasg** [comment]
Hello @nicelhc13, thanks for this issue. I cc @azadcse who is the author of LACC.
There is a fix for this which is currently under testing.

**Comment by szarnyasg** [comment]
This has now been fixed by PR #23.

**Comment by nicelhc13** [comment]
Thank you very much!
