### ISSUE TITLE
LAGraph_mmread needs more information on errors

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/LAGraph#21]
I was reading an mtx file I created and got the following:

```
reading input graph: Data/hpec_coauthors.mtx
LAGraph_mmread: bad type
GrB failure: [5] 
```

It would be helpful to provide more information regarding the error, especially the line number in the file it was parsing.  I did not know if this is because I forgot to put 'general' in the header or if it was because I was incorrectly using zero based indices in my file.  Bad on me as I changed both things at once and the error went away.

**Comment by DrTimothyAldenDavis** [comment]
Yes, we need to add a uniform error reporting method, like GrB_error in
GraphBLAS.

I really don't like GrB_error, though.  It requires thread-local-storage to
keep track of the
last error, and that makes it a real pain to implement.  I would prefer to
have a simpler
thread-safe method where the status and error message are returned directly
to the caller,
without requiring thread-local-storage to be used.

But I can at least see about fixing this particular error message to make
it more useful.

**Comment by DrTimothyAldenDavis** [comment]
The messages are more informative now.
