### ISSUE TITLE
LAGraph_ktruss should also use an algorithm that is not dependent on SuiteSparse extensions

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/LAGraph#24]
I am looking at LAGraph_ktruss.c and it currently requires SuiteSparse extensions AND a specific version.  There is an ktruss algorithm that can be implemented using no extensions and should be implemented in the "#else" section on lines 171-174

**Comment by DrTimothyAldenDavis** [comment]
I haven't written one yet.  It's on my TODO list.

**Comment by mcmillan03** [comment]
TzeMeng and I wrote C and GBTL versions last year

**Comment by DrTimothyAldenDavis** [comment]
Can you add it to the LAGraph_ktruss.c file?  It would be great to have a
version that sticks with the pure GraphBLAS API,
with no GxB* extensions.

There's also an LAGraph_allktruss.c function, which is a straightforward
extension of ktruss.

**Comment by mcmillan03** [comment]
My biggest blocker - besides time - is getting it to fit within some style and testing framework for LAGraph. I am also sitting on the delta stepping code. 

Any suggestions about how best to proceed that gets code in the repo with the smallest effort and meets minimal requirements?

**Comment by DrTimothyAldenDavis** [comment]
The testing framework for ktruss is already there, so that shouldn't be a
problem.  I could also test it myself if you add the code the
LAGraph_ktruss.c;  I would just temporarily disable the
SuiteSparse-specific part of the code.

**Comment by DrTimothyAldenDavis** [comment]
Still not done, but now the v2.0 C API has GrB_select, so this will be simple to do.

**Comment by DrTimothyAldenDavis** [comment]
Done.  It's all GrB now, as is the All-K-truss method.
