### ISSUE TITLE
MxM() question

### ISSUE THREAD

**Issue by nicelhc13** [GraphBLAS/LAGraph#25]
Hello,

I am trying to understand MxM() better and made some test codes.
However, it does not produce expected results.
Could you check the below test cases?

(I am not sure whether this repository is the proper place  where I can report this.
If it is not, I apologize it and will close this issue.)

   ```
 /*
     A, B and M are uint32, 3x3 matrix. 
     Assume that [] represents a row and inner , represents a column.
     A: [1, 0, 1][2, 1, 4][1, 0, 0]
     B: [1, 0, 1][2, 0, 4][1, 0, 0]
    M: [1, 0, 0][0, 1, 0][0, 0, 1] 
 */
    GrB_Matrix_new (&A, GrB_UINT32, 3, 3); 
    GrB_Matrix_new (&B, GrB_UINT32, 3, 3); 
    GrB_Matrix_new (&M, GrB_UINT32, 3, 3); 

    GrB_Matrix_setElement(A, 1, 0, 0); 
    GrB_Matrix_setElement(A, 1, 1, 1); 
    GrB_Matrix_setElement(A, 1, 0, 2); 
    GrB_Matrix_setElement(A, 2, 1, 0); 
    GrB_Matrix_setElement(A, 4, 1, 2); 
    GrB_Matrix_setElement(A, 1, 2, 0); 
 
    GrB_Matrix_setElement(B, 1, 0, 0); 
    GrB_Matrix_setElement(B, 1, 0, 2); 
    GrB_Matrix_setElement(B, 2, 1, 0); 
    GrB_Matrix_setElement(B, 4, 1, 2); 
    GrB_Matrix_setElement(B, 1, 2, 0); 

    GrB_Matrix_setElement(M, 1, 0, 0); 
    GrB_Matrix_setElement(M, 1, 1, 1); 
    GrB_Matrix_setElement(M, 1, 2, 2); 
    GrB_Matrix_setElement(M, 1, 3, 3); 
    GrB_wait();
```
`
Above codes are used for A, B and M matrix configurations.

1) GrB_mxm(A, M, NULL, LAGraph_PLUS_TIMES_UINT32, B, B, NULL);
The above mxm should produce this A:
[2, 0, 0][0, 0, 0][0, 0, 1]
Because BxB shoud [2, 0, 1][6, 0, 2][1, 0, 1] and masking would remove 
entries except diagonal.

However, the test code produces 
[1, 0, 1][2, 0, 4][1, 0, 1]

2) GrB_mxm(B, M, NULL, LAGraph_PLUS_TIMES_UINT32, B, B, NULL);
The above mxm should produce this B:
[2, 0, 0][0, 0, 0][0, 0, 1]

However, the result is:
[2, 0, 1][2, 0, 4][1, 0, 1]

Both were computed by Gustavson mxm().

Could you give any advice on this?
Thank you

**Comment by szarnyasg** [comment]
Hi @nicelhc13, I am not the author but I think the issue here is that you expect `GrB_mxm` to clear the result matrix. However, it does not do so by default - you need to pass a descriptor to get this behavior. The details of this are in the [TOMS paper](http://faculty.cse.tamu.edu/davis/publications_files/toms_graphblas.pdf) and in Sec. 4.11. of the user guide:

> The internal representation is opaque to the user, but in this User Guide the five descriptor fields of a descriptor desc are illustrated as an array of five items, as described in the list below. The underlying implementation need not be an array:
• `desc [GrB_OUTP]` is a parameter that modifies the output of a GraphBLAS operation. Currently, there are two possible settings. **In the default case, the output is not cleared,** and C<M> = Z = C ⊙ T is computed as-is, where T is the results of the particular GraphBLAS operation. In the non-default case, Z = C ⊙ T is first computed, using the results of T and the accumulator ⊙. After this is done, if the `GrB_OUTP` descriptor field is set to `GrB_REPLACE`, then the output is cleared of its entries. Next, the assignment Ch<M> = Z is performed.

```c
    GrB_Descriptor desc;
    GrB_Descriptor_new (&desc);
    GrB_Descriptor_set (desc, GrB_OUTP, GrB_REPLACE);

    GrB_mxm(A, M, NULL, LAGraph_PLUS_TIMES_UINT32, B, B, desc);
    GxB_print(R2, GxB_SHORT);
```

Output:
```console
GraphBLAS matrix: A 
nrows: 3 ncols: 3 max # entries: 2
format: standard CSR vlen: 3 nvec_nonempty: 2 nvec: 3 plen: 3 vdim: 3
hyper_ratio 0.0625
GraphBLAS type:  uint32_t size: 4
last method used for GrB_mxm, vxm, or mxv: heap
number of entries: 2 
row: 0 : 1 entries [0:0]
    column 0: uint32 2
row: 2 : 1 entries [1:1]
    column 2: uint32 1
```

And in a separate run:
```c
    GrB_mxm(B, M, NULL, LAGraph_PLUS_TIMES_UINT32, B, B, desc);
    GxB_print(B, GxB_COMPLETE);
```

Output:
```
GraphBLAS matrix: B 
nrows: 3 ncols: 3 max # entries: 2
format: standard CSR vlen: 3 nvec_nonempty: 2 nvec: 3 plen: 3 vdim: 3
hyper_ratio 0.0625
GraphBLAS type:  uint32_t size: 4
last method used for GrB_mxm, vxm, or mxv: heap
number of entries: 2 
row: 0 : 1 entries [0:0]
    column 0: uint32 2
row: 2 : 1 entries [1:1]
    column 2: uint32 1
```

**Comment by nicelhc13** [comment]
Hello @szarnyasg 
Thank you for your answer.
For the second question, I understood it.

But still the first case generates different results from my expectation..
The entry (0, 0) of output A in the first case should 2. Since it is masked, (without complemented descriptor) it should be computed regardless of the replace descriptor.

Could you correct my misunderstanding?
Thank you!

**Comment by szarnyasg** [comment]
I think the value is there in the output:

```
number of entries: 2 
row: 0 : 1 entries [0:0]
    column 0: uint32 2
row: 2 : 1 entries [1:1]
    column 2: uint32 1
```

Which corresponds to matrix:

```
2  0  0
0  0  0
0  0  1
```

**Comment by nicelhc13** [comment]
Oh I understood.
The right above is using replace descriptor.
But I did not use the descriptor.
I looked into the code and your explanation again. Now I totally understood.
Yes I confused between mask and replace descriptors.
In addition, my test code has minor bug, which produces [1, 0, 1] [2, 0, 4] [1, 0, 1].
[2, 0, 1][2, 0, 4][1, 0, 1] is correct answer and I got it.

Thank you!
