### ISSUE TITLE
How to iterate on all components of the graph?

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#36]
I am working on the analysis of a graph with my Master's student, @marci543. We have a mid-sized, very sparse graph (60M vertices, 100M edges), which consists of ~10M components. We are looking for directed cycles of length 4-6-... in each component.

Splitting the graph to connected components is easy: running LACC returns the component ids (`comp_ids`) for each vertex in a vector. However, the next step is trickier: how do we iterate on all components and extract the corresponding submatrix?

I think this problem can be tackled in many ways, using select, extract, masks, etc. For now, I came with the following pseudo-code but I am not sure this is the best approach:

```
uniq_comps = unique(comp_ids)
for i in 1:size(uniq_comps)
   GxB_Vector_select: select vector v from comp_ids where value = uniq_comps[i]
   GrB_Vector_extractTuples: extract array of row indices I from v
   GrB_Matrix_extract: extract B from A where row indices and column incides are I
   # perform the rest of the computation on matrix B
```

**Comment by DrTimothyAldenDavis** [comment]
At first glance that sounds reasonable.

It would be nice if there were a kind of bulk way of doing it without the
outer for loop, but I don't see one just now.

I think it might be faster to try the following, which limits the amount of
work done within each iteration.

First, permute the matrix by sorting the component ids, then using that
permutation with GrB_extract (or GrB_assign) to create
the permuted matrix.  Let s be an integer vector of length equal to the #
of components, which is the cumulative sum of the sizes of
the components.  Then component k is at rows/columns s[k] to s[k+1]-1.

Then extracting each component with GrB_extract will be very fast, using
the SuiteSparse:GraphBLAS extension to the indexing,
which allows you to specify 3 integers (lo, inc, hi) for the equivalent of
the MATLAB colon notation lo:inc:hi.  That kind of GrB_extract
is very fast, but I'm not sure how fast it will be compared with your
approach.  This approach also requires a permuted copy of the
matrix to be made, which might be a limitation.
