### ISSUE TITLE
Cannot include in C++ code due to restrict

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#49]
@Aznaveh, the current code cannot be included in C++ code due to the use of the [`restrict` keyword](https://en.wikipedia.org/wiki/Restrict) in pagerank3c. This breaks our current Graphalytics driver.

https://github.com/GraphBLAS/LAGraph/blob/f2a5acde2a59d6899b463f583a2c7f2ae93b9008/Include/LAGraph.h#L850-L858

I am not an expert in C/C++ interop - how should we work around this?

**Comment by Aznaveh** [comment]
I have not worked on pagerank3c; my work was basically on pagerank3a and pagerank3b. 
However, it seems that the word `restrict` doesn't add any functionality. It is safer to have it but if it breaks anything I think @DrTimothyAldenDavis  can remove it.

**Comment by DrTimothyAldenDavis** [comment]
That improves performance, by telling the compiler that all accesses to that array are through that pointer.  We can use an #define for it, so it appears when compiled as C code, but not when it is compiled by a C++ compiler.  Removing it doesn't change the functionality, but it would reduce performance for the C case.
