### ISSUE TITLE
How to add include directories for tests?

### ISSUE THREAD

**Issue by aydinbuluc** [GraphBLAS/LAGraph#60]
Hello,

I have my GraphBLAS installed under /usr/local/include

In the CMakeLists.txt, I comment out
include_directories ( ../GraphBLAS/Include )

and uncomment
include_directories ( /usr/local/include )

This makes it pass "make" and "make install"

Yet, I can't make the tests. "make tests" fails due to not being able to find GraphBLAS.h

How can I pass the include directory to top-level makefile so all tests build? I can of course manually change each and every makefile within separate tests/ components but it is a pedestrian solution.

Thanks,
- Aydin

**Comment by DrTimothyAldenDavis** [comment]
I solve this in two ways.  First, 'make install' should put the GraphBLAS.h
include file in a place where any "#include <GraphBLAS.h" should work.  I
do this on my laptop, where I can do "sudo make install" for GraphBLAS.  if
this fails then there is something wrong with your installation.  The
compiler should be able to look into /usr/local/include.

The second solution (if you don't have sudo) is to place LAGraph and
GraphBLAS side-by-side, and then the ../GraphBLAS/Include will work.  On my
desktop, I also have to add /home/davis/stuff/GraphBLAS/build to my
LD_LIBRARY_PATH, and also /home/davis/stuff/LAGraph/build.

**Comment by szarnyasg** [comment]
> The second solution (if you don't have sudo) is to place LAGraph and
GraphBLAS side-by-side, and then the ../GraphBLAS/Include will work. 

We are using the side-by-side solution in the CI build: https://github.com/GraphBLAS/LAGraph/blob/master/.travis.yml

Note that even though we have `sudo` rights in CI, we wanted to make a single script that handles both Linux and Mac OS builds. The latter does not have `ldconfig` which would have slightly complicated things so we opted against using `sudo make install`. Overall, I think the current CI configuration is pretty elegant.

@aydinbuluc did any of Tim's proposed solutions work for your use case?

**Comment by DrTimothyAldenDavis** [comment]
I think the FindGraphBLAS cmake method now fixes this.
