### ISSUE TITLE
GraphBLAS organization member must activate TravisCI for LAGraph repo

### ISSUE THREAD

**Issue by michelp** [GraphBLAS/LAGraph#67]
The final step in activating travis CI builds is enabling it the repo on the Travis site.  Step 3 is what remains:

https://docs.travis-ci.com/user/tutorial/

alternatively someone can make me a repo owner for LAGraph and I'll take care of it.

**Comment by ScottKolo** [comment]
Done - Travis CI has been activated for the LAGraph repo.

**Comment by michelp** [comment]
@ScottKolo hmm, I'm not seeing any builds on travis:

https://travis-ci.org/GraphBLAS/LAGraph

is it possible you accidentally enabled it for your own fork instead of the upstream?

**Comment by ScottKolo** [comment]
Travis builds are usually triggered on a push. I’m not aware of any way to trigger a build any other way.

**Comment by michelp** [comment]
Hmm good point, although there's usually a "trigger build" button on travis, maybe it needs to notice the travis config file first on a push, do you mind making a small punctuation change to the readme and pushing it to test triggering the build?

**Comment by ScottKolo** [comment]
i just made a dummy commit and that triggered a build. 👍
