### ISSUE TITLE
Building large matrices incrementally causes memory reallocation error

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#72]
I tried to use the `mtx2bin` test file to convert the `graph500-29.mtx` Graphalytics data set (233M vertices, 8.5B edges) from Matrix Market to binary (`.grb`) format. However, the code fails:

```bash
~/git/LAGraph/Test/BinRead (master) $ /usr/bin/time -v ~/git/LAGraph/Test/BinRead/build/mtx2bin ~/matrices/graph500-29.mtx ~/grb/graph500-29.grb
infile:  /home/ubuntu/matrices/graph500-29.mtx
outfile: /home/ubuntu/grb/graph500-29.grb
SuiteSparse:GraphBLAS Feb 20, 2020
mtx2bin: malloc.c:4597: _int_realloc: Assertion `ncopies >= 3' failed.
Command terminated by signal 6
        Command being timed: "/home/ubuntu/git/LAGraph/Test/BinRead/build/mtx2bin /home/ubuntu/matrices/graph500-29.mtx /home/ubuntu/grb/graph500-29.grb"
        User time (seconds): 1218.76
        System time (seconds): 78.18
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 21:37.67
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 91094052
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 22772829
        Voluntary context switches: 3
        Involuntary context switches: 109315
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

Judging by the lack of "read time" in the output, the code failed during reading the matrix.

Update: I tried to load the Graphalytics edge file (`.e`) manually and instrumented the code to see where it fails. It failed after 4.2B edges, a number which is suspiciously close to 2^32.
```
[...]
- Edge no.3900000000 processed
- Edge no.4000000000 processed
- Edge no.4100000000 processed
- Edge no.4200000000 processed
converter: malloc.c:4597: _int_realloc: Assertion `ncopies >= 3' failed.
```

**Comment by szarnyasg** [comment]
I refined the instrumentation a bit as follows:

```cpp
    uint64_t i;
    while (std::getline(edge_file, line)) {
        i++;
        std::istringstream line_stream{line};
        line_stream >> src;
        line_stream >> trg;
        // use 0-based indexing
        Vertex src_mapped = mapping[src] - 1;
        Vertex trg_mapped = mapping[trg] - 1;

        if (parameters.weighted) {
            line_stream >> weight_string;
            OK(GrB_Matrix_setElement_FP64(A, std::stod(weight_string), src_mapped, trg_mapped))
        } else {
            OK(GrB_Matrix_setElement_BOOL(A, 1, src_mapped, trg_mapped))
        }
        if (i > 4294960000) {
            std::cout << "- Edge no." << i << " processed" << std::endl;
        }
    }
```

My hypthesis turned out to be correct. The code fails after edge no. `2^32` (`4294967296`).

```bash
- Edge no.4294967294 processed                                                
- Edge no.4294967295 processed                                    
- Edge no.4294967296 processed
converter: malloc.c:4597: _int_realloc: Assertion `ncopies >= 3' failed.
```

**Comment by michelp** [comment]
Hmm, that assertion is deep inside the glibc implementation of realloc:

https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/malloc/malloc.c#L4601

What OS version are you running on?

**Comment by szarnyasg** [comment]
Ubuntu 18.04 and using Intel C++ Compiler (forgot to add this important detail).

**Comment by michelp** [comment]
Is it possible you're using a 32 bit version of 18.04?  What does `uname -i` return?

**Comment by szarnyasg** [comment]
I find that unlikely - the machine has 768 GBs of memory and running a 64-bit Ubuntu server installed by the cloud provider. I cannot check `uname -i` because the machine is powered off due to $$ constraints :-) but I'm certain it'd return `x86_64`.

**Comment by michelp** [comment]
Since it takes 20+ hours for you to reproduce it, I wonder if it would be worth a short C program to test creating more than 2^32 elements, say inserting random values with setElement in a tight loop, might be able to hit the limit faster and it would rule out a problem with mmread, which I don't see any obvious problem with.

**Comment by szarnyasg** [comment]
@michelp good point. Here's a minimal working example (just thrown in `mtx2bin.c` out of laziness): https://github.com/szarnyasg/LAGraph/blob/mtx2bin-mwe/Test/BinRead/mtx2bin.c

This creates a 5B × 5B matrix and inserts `true` values into its diagonal. I'll copy its output in a moment but it's essentially the same as before:

```
[...]
- Edge no.3900000000 processed
- Edge no.4000000000 processed
- Edge no.4100000000 processed
- Edge no.4200000000 processed
converter: malloc.c:4597: _int_realloc: Assertion `ncopies >= 3' failed.
```

**Comment by DrTimothyAldenDavis** [comment]
It sounds like something is broken in your realloc.  This should work
fine.  Can you try recompiling with a pure C compiler instead of C++?

The setElement function calls GB_Pending_realloc, eventually, to realloc
the set of pending tuples.  This calls GB_realloc_memory, then
GB_Global_realloc_function in Source/GB_Global.c.  That function calls the
GB_Global.realloc_function which by default is a pointer to the ANSI C11
realloc function.

The pointer is initialized by GrB_init, or GxB_init, and defaults to a
pointer to the realloc function.

Try this.  In GB_Global.c, find the GB_Global_realloc_function (line 395).
In that function, add this printf:

printf ("realloc: %p %p\n", realloc, GB_Global.realloc_function) ;

maybe you're getting the wrong realloc function.  it looks like your
realloc is not 64-bit safe, but just 32-bit.

Can you run ldd to determine which realloc or glibc is being used?

**Comment by michelp** [comment]
I don't have a machine big enough at the moment to reproduce this, but I think the next step would be trying to see if it's related to the platform or Intel compiler.

Another curiosity is maybe it's a side effect of disabling mmap allocation:

https://github.com/GraphBLAS/LAGraph/blob/master/Source/Utility/LAGraph_init.c#L64

**Comment by szarnyasg** [comment]
@DrTimothyAldenDavis 

I'm running the code on a smaller machine which has does not have ICC configured so I've just used GCC:
```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```

The `printf ("realloc: %p %p\n", realloc, GB_Global.realloc_function) ;` command in prints:

```
Start inserting edges
- Edge no.0 processed
realloc: 0x7f72a5429c30 0x7f72a5429c30
```

`ldd` shows `/lib/x86_64-linux-gnu/libc.so.6`:
```
$ ldd build/mtx2bin 
        linux-vdso.so.1 (0x00007ffea75e8000)
        libgraphblas.so.3 => /home/ubuntu/git/LAGraph/Test/BinRead/../../../GraphBLAS/build/libgraphblas.so.3 (0x00007fc6e7e33000)
        liblagraph.so.0 => /home/ubuntu/git/LAGraph/Test/BinRead/../../build/liblagraph.so.0 (0x00007fc6e7bd9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc6e77e8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc6e744a000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fc6e721b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc6e6ffc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc6ec04a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc6e6df8000)
```

**Comment by szarnyasg** [comment]
@michelp you're right! Dropping the 3 `mallopt` lines fixed the problem. Trying to pinpoint whether it's the mmap one.

```
$ git diff
diff --git a/Source/Utility/LAGraph_init.c b/Source/Utility/LAGraph_init.c
index 2ba1ac3..1271978 100644
--- a/Source/Utility/LAGraph_init.c
+++ b/Source/Utility/LAGraph_init.c
@@ -61,9 +61,6 @@ GrB_Info LAGraph_init ( )
     // several seconds to free a large block of memory.  For this to be
     // effective, LAGraph_init must be called before the user program does any
     // mallocs or frees itself.
-    mallopt (M_MMAP_MAX, 0) ;           // disable mmap; it's too slow
-    mallopt (M_TRIM_THRESHOLD, -1) ;    // disable sbrk trimming
-    mallopt (M_TOP_PAD, 16*1024*1024) ; // increase padding to speedup malloc
     #endif
     info = LAGraph_xinit (malloc, calloc, realloc, free, true) ;
     #endif
```

**Comment by szarnyasg** [comment]
It was the indeed `mmap` line.

```
-    mallopt (M_MMAP_MAX, 0) ;           // disable mmap; it's too slow
```

**Comment by michelp** [comment]
Hmm, so I know Tim disabled mmap to make the gap benchmarks faster by disabling mmap, maybe another approach that achieves that goal but fixes this is to set the MAX very high, say 1-2GB.

This answer also has some interesting details:

https://stackoverflow.com/a/53624488

"This suggests to me that man mallopt saying

Setting this parameter to 0 disables the use of mmap(2)
for servicing large allocation requests.

isn't quite true: It will still mmap when it wants to create a new arena."

**Comment by DrTimothyAldenDavis** [comment]
Oops.  I didn't realize that would break matrices larger than 2^32 entries.  I'll see about replacing that line with something else that is still fast, but allows for big mallocs.

**Comment by DrTimothyAldenDavis** [comment]
The LAGraph_MMRead no longer uses GrB_Matrix_setElement.  Instead, it allocates arrays of fixed sizes and fills them, then uses GrB_Matrix_build.  This means that internally, I don't need to call realloc.

However, the mmap setting still appears in the LAGraph_Init method.  That should be examined to see if it's still necessary for getting good performance on the GAP benchmarks.

**Comment by DrTimothyAldenDavis** [comment]
Realloc is gone in LAGraph_MMRead, and I've now moved the calls to mallopt into the demo_init, and out of LAGraph_Init.
