### ISSUE TITLE
LAGraph_pattern is not implemented for vectors

### ISSUE THREAD

**Issue by marci543** [GraphBLAS/LAGraph#80]
[LAGraph_pattern()](https://github.com/GraphBLAS/LAGraph/blob/4a4e83e7268a3d9486635519f689037762a175b4/Include/LAGraph.h#L765-L770) function is implemented only for matrices. I think it would be useful to have it also for vectors.

**Comment by DrTimothyAldenDavis** [comment]
This is now called LAGraph_Structure, and it is a lot simpler in the v2.0 C API.  It would be simple now to add an LAGraph_Vector_Structure method.

**Comment by DrTimothyAldenDavis** [comment]
Added, as LAGraph_Vector_Structure.  See also LAGraph_Matrix_Structure.
