### ISSUE TITLE
Optimize LAGraph_lcc

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#81]
[`LAGraph_lcc`](https://github.com/GraphBLAS/LAGraph/blob/master/Source/Algorithm/LAGraph_lcc.c) could greatly benefit from the tricks emloyed in [`LAGraph_tricount`](https://github.com/GraphBLAS/LAGraph/blob/master/Source/Algorithm/LAGraph_tricount.c), namely, using the `GxB_PLUS_PAIR_INT64` semiring (to avoid looking into the values of the matrices under multiplication) and the `GrB_DESC_S` or similar descriptor (to avoid looking into the values in the mask).

**Comment by DrTimothyAldenDavis** [comment]
This can now be done with the new GrB_ONEB_INT64 operator, and the LAGraph_plus_one_int64 semiring.  LAGraph_lcc can be pure GrB with no GxB extensions, and faster as well.

**Comment by szarnyasg** [comment]
Fixed via #185.
