### ISSUE TITLE
Simple installation under Ubuntu 20.04

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#82]
In Ubuntu 20.04 (released last week), GraphBLAS 3.2.0 can be installed through its APT package manager.

So now LAGraph can be built & installed as simply as:

```bash
sudo apt install libgraphblas3
git clone --depth 1 --branch v3.2.0 https://github.com/DrTimothyAldenDavis/GraphBLAS
git clone https://github.com/GraphBLAS/LAGraph
cd LAGraph
sudo make install
```

Maybe it's worth mentioning this in the README.

**Comment by szarnyasg** [comment]
I tinkered with this a bit more in Docker. It turned out that the script above does not work, as it ultimately returns:

```console
/usr/bin/ld: cannot find -lgraphblas
collect2: error: ld returned 1 exit status
```

(I probably missed this during the last run.)

To fix this, I used this trick ([source](https://stackoverflow.com/a/21647591/3580502)):

```bash
ln -s /usr/lib/x86_64-linux-gnu/libgraphblas.so.3 /usr/lib/x86_64-linux-gnu/libgraphblas.so
```

But there might be a more elegant way around the problem.

**Comment by michelp** [comment]
Hi Gabor,

What is in the libgraphblas3 package? It seems odd to me that you install the package but clone and build SuiteSparse anyway, am I missing something?

**Comment by szarnyasg** [comment]
@michelp 

`libgraphblas3` contains the `so` files of SuiteSparse:GraphBLAS: https://packages.ubuntu.com/focal/amd64/libgraphblas3/filelist

I simply clone GraphBLAS next to the LAGraph directory but do not build GraphBLAS. By default, LAGraph looks for the GraphBLAS sources file in `../GraphBLAS` so it's able to locate the source files this way and proceed with its build.

Another alternative that we use in one of our other projects is to use the `CPATH` variable to pass the location of the GraphBLAS `Include` directory (`export CPATH=/some/path/GraphBLAS/Include/`).

I think according to the typical packaging convention, a `libgraphblas3-dev` package could be defined that holds the source files of GraphBLAS. (But I've never packaged DEBs so I might be wrong.)

**Comment by michelp** [comment]
I see, missed the part where you don't build it. :)  I agree, `libgraphblas3-dev` would be nice to skip the first clone step.  It might be worth contacting the package maintainer about that, if there were a -dev package, I could depend on it as well for pygraphblas.  Do you know who is maintaining the packages?

**Comment by szarnyasg** [comment]
The maintainer is Sébastien Villemot, I think @DrTimothyAldenDavis has his contact info.

**Comment by michelp** [comment]
As you likely saw in Sébastien's email the solution is to install `libsuitesparse-dev`.

**Comment by michelp** [comment]
I've confirmed these packages work with pygraphblas, and pushed a new `graphblas/pygraphblas-minimal` docker image from the 20.04 base image, only 250MB!

https://hub.docker.com/repository/registry-1.docker.io/graphblas/pygraphblas-minimal/tags?page=1

Dockerfile:

https://github.com/michelp/pygraphblas/blob/master/Dockerfile-minimal

**Comment by szarnyasg** [comment]
@michelp thanks for investigating this. It indeed works for our Graphalytics image as well:

https://github.com/ftsrg/ldbc-graphalytics-platform-graphblas/commit/82ab271d080ac27791d1b7f65bf1009dd65ac3bb

**Comment by szarnyasg** [comment]
@michelp I submitted PR#85 to resolve this. I could not add you as a review but let me know if you have any comments.

**Comment by michelp** [comment]
lgtm :+1:
