### ISSUE TITLE
Alternative PageRank implementation

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#9]
## Summary
I am working with @hegyibalint on an alternative PageRank implementation, which complies with the [LDBC Graphalytics specification](https://ldbc.github.io/ldbc_graphalytics_docs/graphalytics_spec.pdf). The main difference between the two definitions is that the [current PageRank implementation](https://github.com/GraphBLAS/LAGraph/blob/master/Source/Algorithm/LAGraph_pagerank.c) does not consider "dangling vertices", while the new ones does. I propose to call the new algorithm `LAGraph_pagerank_dangling`.

### Problem

As discussed in the [LAGraph paper](https://github.com/GraphBLAS/LAGraph/blob/master/Doc/lagraph-grapl19.pdf), the current PageRank implementation is based on N. Satish et al. ["Navigating the maze of graph analytics frameworks using massive graph datasets"](https://dl.acm.org/citation.cfm?id=2588555.2610518) paper, published at SIGMOD 2014. However, there are many PageRank variants and LDBC Graphalytics requires a different one.

### History

PageRank variants have a long history. A good summary on potential approaches to handle dangling vertices is given in N. Eiron et al.'s ["Ranking the web frontier"](https://dl.acm.org/citation.cfm?doid=988672.988714) paper, published at WWW 2004
In particular a section titled "Handling dangling pages" states that:

> [...] In the original Pagerank paper [28] the authors suggested simply removing the links to dangling pages from the graph, and calculating the PageRank on the remaining pages. After doing so it was suggested that they can be “added back in” without significantly affecting the results, but the details of how to do this are lacking (as is the analysis of the effect from dangling nodes). In [23] the authors suggested removing the dangling nodes and then re-inserting them “for the last few iterations”. Note that removing the dangling links entirely will skew the results on the non-dangling nodes somewhat, since the outdegrees from the pages are adjusted to reflect the lack of links to dangling nodes. [...]
> One alternative method for handling dangling pages is to jump to a randomly selected page with probability 1 from every dangling node. This approach is mentioned in [23] and treated more formally as follows. [...]

The alternative method described above is the one used by the Graphalytics framework:

![image](https://user-images.githubusercontent.com/1402801/61735223-c9d4d380-ad83-11e9-8947-17d3e91e50c8.png)

### Reference code

This algorithm can be implemented in Julia as follows:

```julia
out = A*ones(N)
D = map(x -> x == 0 ? 1.0 : 0.0, out)
pr = ones(N)/N
for i in 1:iterations
    teleport = (1-d) / N
    importance = d * A'*(pr./out)
    dangling = d/N * sum(pr.*D)
    global pr = teleport .+ importance .+ dangling
end
```

### Naming

Originally, I was inclined to simply call this `PageRank2` but it appears that this name has already been taken by the Matlab function [`dpagerank2`](https://github.com/GraphBLAS/LAGraph/blob/master/Test/PageRank/dpagerank2.m) in the repository. As the name was already taken, I propose to call the new algorithm `LAGraph_pagerank_dangling` but I am open to other ideas as well.

**Comment by DrTimothyAldenDavis** [comment]
Sounds great to me.  I'm OK with the name pagerank2.  We can rename the MATLAB function.  The name of that MATLAB function is not important.

**Comment by szarnyasg** [comment]
Great. PR #10 reflected this decision.
