### ISSUE TITLE
How to multiply a vector by a scalar

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#90]
I'd like to multiply a vector `v` with a scalar value `k`, i.e. `v*k` in MATLAB syntax.

So far, the quickest way I found is to create an equal-sized vector `multiplier`, fill it with `k` values and use element-wise multiplication:

```c
GrB_assign(multiplier, NULL, NULL, level, GrB_ALL, k, NULL);
GrB_eWiseMult(v, NULL, NULL, GrB_TIMES_UINT64, v, multiplier, NULL);
```

Is there a simpler way to achieve this?

**Comment by mcmillan03** [comment]
I see two other options:

Option 1:  Create a user defined unary operator that stores k and
multiplies the input by that value, and then use apply.
Option 2: Wait for GraphBLAS 1.3 version of apply that takes a binary
operator (TIMES) and a constant (k).

**Comment by DrTimothyAldenDavis** [comment]
I need to write the v1.3 function.  I hope to tackle that soon.  That will
be the fastest method.  In the meantime, the scalar has to be expanded to
pattern of the vector v.

it's too costly to expand the scalar to dense.

I do this in my MATLAB interface.  See

https://github.com/DrTimothyAldenDavis/GraphBLAS/blob/master/GraphBLAS/@GrB/times.m

which calls:

https://github.com/DrTimothyAldenDavis/GraphBLAS/blob/master/GraphBLAS/%40GrB/private/gb_emult.m

which then calls the following to expand a scalar to the pattern of another
matrix:

https://github.com/DrTimothyAldenDavis/GraphBLAS/blob/master/GraphBLAS/%40GrB/private/gb_expand.m

which then calls a MATLAB mexFunction wrapper for GxB_subassign (GrB_assign
would be fine to),
which does:

Let S be the matrix with the pattern you want to expand the scalar too.  It
is used as a mask

GrB_Matrix_new (&C, type, m, n)
GxB_Matrix_subassign_TYPE (C, S, NULL, scalar, GrB_ALL, GrB_ALL,
GrB_DESC_S) ;

that gives you the operation C<S>=scalar.  It efficiently assigns the
scalar to C, where C has the
exact pattern of S.

Then use GrB_eWiseMult to do the multiply.

**Comment by szarnyasg** [comment]
Thanks! This indeed seems more efficient.

So for an `UINT64` scalar, `S = S * scalar` can be computed with:
```c
GrB_Matrix_new(&C, type, m, n);
GxB_Matrix_subassign_UINT64(C, S, NULL, scalar, GrB_ALL, m, GrB_ALL, n, GrB_DESC_S);
GrB_eWiseMult(S, NULL, NULL, GrB_TIMES_UINT64, S, C, NULL);
```

And to compute `v = v * scalar`:
```c
GrB_Vector_new(&u, type, n);
GxB_Vector_subassign_UINT64(u, v, NULL, scalar, GrB_ALL, n, GrB_DESC_S);
GrB_eWiseMult(v, NULL, NULL, GrB_TIMES_UINT64, v, u, NULL);
```

`GrB_*_assign_<type>` also works if one does not have `GxB_` functions at hand.

**Comment by DrTimothyAldenDavis** [comment]
Yes, those should work.

GrB_*_assign_[type] is identical to GxB_subassign_[type] when I and J are
GrB_ALL, so GrB*assign*type should be used instead.  Then all of it can be
done with the v1.3 spec (using the new structural mask, GrB_DESC_S, which I
now support).

**Comment by szarnyasg** [comment]
Support for binary ops with `GrB_apply` has been added to https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v3.3.0draft8 - so this will be the preferred way from 3.3.0. Thanks!

**Comment by DrTimothyAldenDavis** [comment]
Minor correction:  my 'git push' for draft8 left out the Source folder, by mistake.  I've fully pushed the update now.  It's draft9 that now has GrB_apply with binary operators:  https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v3.3.0draft9
