### ISSUE TITLE
LAGraph_Vector_to_dense produces incorrect result with SuiteSparse v3.3.0draft5

### ISSUE THREAD

**Issue by marci543** [GraphBLAS/LAGraph#92]
I added test for `LAGraph_Vector_to_dense` in #91.

The function produces incorrect result if it is built with SuiteSparse v3.3.0draft5. Some non-zero values are missing. ([Branch for test code](https://github.com/szarnyasg/LAGraph/tree/test-vector-to-dense-v3.3.0draft5))
```
  6x1 GraphBLAS uint64_t vector, sparse by col:
  v, 3 entries
    (0,0)   2
    (1,0)   3
    (4,0)   1


  6x1 GraphBLAS uint64_t vector, sparse by col:
  v_dense, 6 entries
    (0,0)   2
    (1,0)   0
    (2,0)   0
    (3,0)   0
    (4,0)   0
    (5,0)   0

  6x1 GraphBLAS uint64_t vector, sparse by col:
  v_dense_ref, 6 entries
    (0,0)   2
    (1,0)   3
    (2,0)   0
    (3,0)   0
    (4,0)   1
    (5,0)   0
```
Test log: https://travis-ci.com/github/szarnyasg/LAGraph/jobs/345416111#L27837

With v3.2.2 the problem is not present ([branch](https://github.com/szarnyasg/LAGraph/tree/test-vector-to-dense-v3.2.2)).
Test log: https://travis-ci.com/github/szarnyasg/LAGraph/jobs/345421717#L26747

Can I ask for some advice, @DrTimothyAldenDavis?

**Comment by marci543** [comment]
The test code is here: https://github.com/szarnyasg/LAGraph/blob/test-vector-to-dense/Test/VectorToDense/vector_to_dense_test.c

**Comment by DrTimothyAldenDavis** [comment]
The test passes in the current (master) version of GraphBLAS, with COMPACT turned off, and I get the expected result.  The current version isn't much different than the 3.3.0draft5, however.

If I turn off -GBCOMPACT in 3.3.0draft5, I get the right result.   If I enable -DGBCOMPACT=1 (as done in the travis tests I think), then I can replicate the wrong answer you're seeing.   So this is an issue with the "COMPACT" option in 3.3.0draft5.

**Comment by DrTimothyAldenDavis** [comment]
Found it.  It was a bug introduced when handling the new complex data types in the C<M>=scalar assignment, which worked for the complex case but then broke the compact case.  I'll tag 3.3.0draft6 shortly, which fixes this issue.

**Comment by marci543** [comment]
Thanks for the fast solution.

**Comment by DrTimothyAldenDavis** [comment]
And thanks for the fast bug report.  I ran the code (with the bug) under my
brutal 100% statement coverage tests in GraphBLAS/Tcov ... and all the
tests passed, because it only shows up with COMPACT (or with user defined
types).  I usually also rerun those tests with COMPACT enabled, before the
final release, but had I missed that I would have published (gasp!) a bug
in the stable version of the code.

I'll be sure to check this condition in my brutal tests.
