### ISSUE TITLE
Reordering matrix rows/columns by degree

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#99]
Reordering the matrix rows/columns by degree is a common optimization and it is already used in `LAGraph_tricount.c`, which makes use of the parallel merge sort in GraphBLAS:

https://github.com/GraphBLAS/LAGraph/blob/51fd40fbc2c230649621f6a630f2b9c3d91194ea/Source/Algorithm/LAGraph_tricount.c#L412

In my work, this could be beneficial for LCC (as its kernel is almost the same as tricount) and bitwise MSBFS (as it would increase the average "density", i.e. the number of 1s in the non-zero UINT64 values thus leading to a more sparse matrix overall).

So it would be worth considering a function with a signature such as `LAGraph_reorder_vertices(GrB_Matrix* A, boolean ascending)`.

Update: I've since discovered that tricount relies on the user providing the `degree` array which is already a candidate to be used as a utility function:

https://github.com/GraphBLAS/LAGraph/blob/b8265ccba651a1344d39e12588749f9f161bd873/Test/TriangleCount/gap_tc_test.c#L230-L242

**Comment by DrTimothyAldenDavis** [comment]
We now have sorting methods in LAGraph, and a method for computing the row and column degrees.  There is also GxB_Vector_sort in the latest v6 of SuiteSparse:GraphBLAS, but this is not in the spec.
